name: ekalipi-tts
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
    build_command: |
      pip install --upgrade pip
      pip install gunicorn
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"
      mkdir -p static/audio tmp
    run_command: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 4
    instance_size_slug: basic-xxs
    instance_count: 1
    env:
      - key: PORT
        value: "8080"
      - key: FLASK_ENV
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "true"
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 15
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3