name: tts-hs-hifigan
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - numpy=1.24.3
  - scipy
  - pytorch
  - torchaudio
  - pyyaml
  - pandas
  - pip:
    - g2p-en
    - indic-unified-parser
